### ISSUE TITLE
想问一下只有主板不同efi需要改哪里

### ISSUE THREAD

**Issue by jeteveux** [hackintosh-club/MAG-B760M-MORTAR-OpenCore#2]
用的b660迫击炮主板，显卡580应该不是问题。想问一下哪里需要改

**Comment by WuLongMiTaoLaiYiDa** [comment]
> 用的b660迫击炮主板，显卡580应该不是问题。想问一下哪里需要改

理论上来说通用

一般不同的就是无线网卡部分
