### ISSUE TITLE
MAG B760M MORTAR MAX WIFI DDR4 + i5 13490F + MSI Radeon RX 6650 XT

### ISSUE THREAD

**Issue by wuziwei** [hackintosh-club/MAG-B760M-MORTAR-OpenCore#4]
请教一下这个配置可以直接下载你的文件吗？
还是需要改什么
MAG B760M MORTAR MAX WIFI DDR4 + i5 13490F + MSI 6650xt

**Comment by WuLongMiTaoLaiYiDa** [comment]
[SSDT-6650XT.zip](https://github.com/hackintosh-club/MAG-B760M-MORTAR-OpenCore/files/13267472/SSDT-6650XT.zip)
add SSDT-6650XT-73EF-GPU-SPOOF.aml  to ACPI folder and config.plist
